// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.BO.Models;

public partial class Booking
{
    public int BookingId { get; set; }

    public int Loiid { get; set; }

    public decimal BookingFee { get; set; }

    public DateTime BookingDate { get; set; }

    public string Status { get; set; }

    public virtual LetterOfIntent Loi { get; set; }
}