// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.BO.Models;

public partial class Car
{
    public int CarId { get; set; }

    public string Model { get; set; }

    public string CarType { get; set; }

    public decimal BasePrice { get; set; }

    public int? Year { get; set; }

    public string Color { get; set; }

    public virtual ICollection<ConsultHistory> ConsultHistories { get; set; } = new List<ConsultHistory>();

    public virtual ICollection<DealerInventory> DealerInventories { get; set; } = new List<DealerInventory>();

    public virtual ICollection<InventoryTransfer> InventoryTransfers { get; set; } = new List<InventoryTransfer>();

    public virtual ICollection<LetterOfIntentDetail> LetterOfIntentDetails { get; set; } = new List<LetterOfIntentDetail>();

    public virtual ICollection<SalesAgreementDetail> SalesAgreementDetails { get; set; } = new List<SalesAgreementDetail>();

    public virtual ICollection<TestDrive> TestDrives { get; set; } = new List<TestDrive>();
}