// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.BO.Models;

public partial class CarDeliverySchedule
{
    public int CarDeliveryScheduleId { get; set; }

    public int CarDeliveryId { get; set; }

    public DateTime ScheduledDate { get; set; }

    public string Note { get; set; }

    public virtual CarDelivery CarDelivery { get; set; }
}