// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.BO.Models;

public partial class CarDelivery
{
    public int CarDeliveryId { get; set; }

    public int SalesAgreementId { get; set; }

    public DateTime DeliveryDate { get; set; }

    public string Status { get; set; }

    public virtual ICollection<CarDeliverySchedule> CarDeliverySchedules { get; set; } = new List<CarDeliverySchedule>();

    public virtual ICollection<PreDeliveryInspection> PreDeliveryInspections { get; set; } = new List<PreDeliveryInspection>();

    public virtual SalesAgreement SalesAgreement { get; set; }
}