// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.BO.Models;

public partial class ConsultHistory
{
    public int ConsultHistoryId { get; set; }

    public int DealerId { get; set; }

    public int CustomerId { get; set; }

    public int SalesPersonId { get; set; }

    public int? CarId { get; set; }

    public decimal? Budget { get; set; }

    public string PaymentMethod { get; set; }

    public DateTime ConsultationDate { get; set; }

    public string Note { get; set; }

    public virtual Car Car { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Dealer Dealer { get; set; }

    public virtual ICollection<LetterOfIntent> LetterOfIntents { get; set; } = new List<LetterOfIntent>();

    public virtual SalesPerson SalesPerson { get; set; }

    public virtual ICollection<TestDrive> TestDrives { get; set; } = new List<TestDrive>();
}