// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.BO.Models;

public partial class CreditDocument
{
    public int CreditDocumentId { get; set; }

    public int CreditAppId { get; set; }

    public string DocumentType { get; set; }

    public string DocumentPath { get; set; }

    public DateTime? UploadDate { get; set; }

    public virtual CreditApplication CreditApp { get; set; }
}