// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.BO.Models;

public partial class CreditApplication
{
    public int CreditAppId { get; set; }

    public int Loiid { get; set; }

    public int? LeasingCompanyId { get; set; }

    public DateTime ApplicationDate { get; set; }

    public string Status { get; set; }

    public virtual ICollection<CreditDocument> CreditDocuments { get; set; } = new List<CreditDocument>();

    public virtual LeasingCompany LeasingCompany { get; set; }

    public virtual LetterOfIntent Loi { get; set; }

    public virtual ICollection<PaymentHistory> PaymentHistories { get; set; } = new List<PaymentHistory>();
}