// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.BO.Models;

public partial class CustomerNotification
{
    public int CustomerNotificationId { get; set; }

    public int CustomerId { get; set; }

    public int? Loiid { get; set; }

    public int? SalesAgreementId { get; set; }

    public string NotificationType { get; set; }

    public string Message { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? ReadDate { get; set; }

    public bool IsRead { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual LetterOfIntent Loi { get; set; }

    public virtual SalesAgreement SalesAgreement { get; set; }
}
