// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.BO.Models;

public partial class CustomerComplaint
{
    public int CustomerComplaintId { get; set; }

    public int CustomerId { get; set; }

    public int? SalesAgreementId { get; set; }

    public DateTime ComplaintDate { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual SalesAgreement SalesAgreement { get; set; }
}