// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.BO.Models;

public partial class CustomerFeedback
{
    public int CustomerFeedbackId { get; set; }

    public int CustomerId { get; set; }

    public int? SalesAgreementId { get; set; }

    public DateTime FeedbackDate { get; set; }

    public int? Rating { get; set; }

    public string Comment { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual SalesAgreement SalesAgreement { get; set; }
}