// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.BO.Models;

public partial class DealerInventory
{
    public int DealerInventoryId { get; set; }

    public int DealerId { get; set; }

    public int CarId { get; set; }

    public int Stock { get; set; }

    public decimal Price { get; set; }

    public double DiscountPercent { get; set; }

    public double FeePercent { get; set; }

    public virtual Car Car { get; set; }

    public virtual Dealer Dealer { get; set; }
}