// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.BO.Models;

public partial class Dealer
{
    public int DealerId { get; set; }

    public string Name { get; set; }

    public string City { get; set; }

    public string Address { get; set; }

    public string PhoneNumber { get; set; }

    public virtual ICollection<ConsultHistory> ConsultHistories { get; set; } = new List<ConsultHistory>();

    public virtual ICollection<DealerInventory> DealerInventories { get; set; } = new List<DealerInventory>();

    public virtual ICollection<InventoryTransfer> InventoryTransferFromDealers { get; set; } = new List<InventoryTransfer>();

    public virtual ICollection<InventoryTransfer> InventoryTransferToDealers { get; set; } = new List<InventoryTransfer>();

    public virtual ICollection<LetterOfIntent> LetterOfIntents { get; set; } = new List<LetterOfIntent>();

    public virtual ICollection<SalesAgreement> SalesAgreements { get; set; } = new List<SalesAgreement>();

    public virtual ICollection<SalesPerson> SalesPeople { get; set; } = new List<SalesPerson>();

    public virtual ICollection<TestDrive> TestDrives { get; set; } = new List<TestDrive>();
}