// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.BO.Models;

public partial class InventoryTransfer
{
    public int InventoryTransferId { get; set; }

    public int FromDealerId { get; set; }

    public int ToDealerId { get; set; }

    public int CarId { get; set; }

    public int Quantity { get; set; }

    public DateTime MutationDate { get; set; }

    public virtual Car Car { get; set; }

    public virtual Dealer FromDealer { get; set; }

    public virtual Dealer ToDealer { get; set; }
}