// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.BO.Models;

public partial class LeasingCompany
{
    public int LeasingCompanyId { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public string PhoneNumber { get; set; }

    public virtual ICollection<CreditApplication> CreditApplications { get; set; } = new List<CreditApplication>();
}