// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.BO.Models;

public partial class LetterOfIntent
{
    public int Loiid { get; set; }

    public int DealerId { get; set; }

    public int CustomerId { get; set; }

    public int SalesPersonId { get; set; }

    public int? ConsultHistoryId { get; set; }

    public int? TestDriveId { get; set; }

    public DateTime Loidate { get; set; }

    public string PaymentMethod { get; set; }

    public string Note { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ConsultHistory ConsultHistory { get; set; }

    public virtual ICollection<CreditApplication> CreditApplications { get; set; } = new List<CreditApplication>();

    public virtual Customer Customer { get; set; }

    public virtual Dealer Dealer { get; set; }

    public virtual ICollection<LetterOfIntentDetail> LetterOfIntentDetails { get; set; } = new List<LetterOfIntentDetail>();

    public virtual ICollection<SalesAgreement> SalesAgreements { get; set; } = new List<SalesAgreement>();

    public virtual SalesPerson SalesPerson { get; set; }

    public virtual TestDrive TestDrive { get; set; }
}