// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.BO.Models;

public partial class LetterOfIntentDetail
{
    public int LoidetailId { get; set; }

    public int Loiid { get; set; }

    public int CarId { get; set; }

    public decimal AgreedPrice { get; set; }

    public decimal? Discount { get; set; }

    public decimal? DownPayment { get; set; }

    public string Note { get; set; }

    public virtual Car Car { get; set; }

    public virtual LetterOfIntent Loi { get; set; }

    public virtual ICollection<SalesAgreementDetail> SalesAgreementDetails { get; set; } = new List<SalesAgreementDetail>();
}