// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.BO.Models;

public partial class PaymentHistory
{
    public int PaymentHistoryId { get; set; }

    public int? SalesAgreementId { get; set; }

    public int? CreditAppId { get; set; }

    public decimal PaymentAmount { get; set; }

    public DateTime PaymentDate { get; set; }

    public string PaymentType { get; set; }

    public virtual CreditApplication CreditApp { get; set; }

    public virtual SalesAgreement SalesAgreement { get; set; }
}