// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.BO.Models;

public partial class PreDeliveryInspection
{
    public int PreDeliveryInspectionId { get; set; }

    public int CarDeliveryId { get; set; }

    public DateTime InspectionDate { get; set; }

    public string InspectorName { get; set; }

    public string Note { get; set; }

    public virtual CarDelivery CarDelivery { get; set; }
}