// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.BO.Models;

public partial class SalesAgreementDetail
{
    public int SalesAgreementDetailId { get; set; }

    public int SalesAgreementId { get; set; }

    public int? LoidetailId { get; set; }

    public int CarId { get; set; }

    public decimal Price { get; set; }

    public decimal? Discount { get; set; }

    public string Note { get; set; }

    public virtual Car Car { get; set; }

    public virtual LetterOfIntentDetail Loidetail { get; set; }

    public virtual SalesAgreement SalesAgreement { get; set; }

    public virtual ICollection<ServiceHistory> ServiceHistories { get; set; } = new List<ServiceHistory>();

    public virtual ICollection<VehicleRegistration> VehicleRegistrations { get; set; } = new List<VehicleRegistration>();

    public virtual ICollection<WarrantyClaim> WarrantyClaims { get; set; } = new List<WarrantyClaim>();
}