// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.BO.Models;

public partial class SalesPerson
{
    public int SalesPersonId { get; set; }

    public int DealerId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<ConsultHistory> ConsultHistories { get; set; } = new List<ConsultHistory>();

    public virtual Dealer Dealer { get; set; }

    public virtual ICollection<LetterOfIntent> LetterOfIntents { get; set; } = new List<LetterOfIntent>();

    public virtual ICollection<SalesAgreement> SalesAgreements { get; set; } = new List<SalesAgreement>();

    public virtual ICollection<TestDrive> TestDrives { get; set; } = new List<TestDrive>();
}