// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.BO.Models;

public partial class SalesAgreement
{
    public int SalesAgreementId { get; set; }

    public int DealerId { get; set; }

    public int CustomerId { get; set; }

    public int SalesPersonId { get; set; }

    public int? Loiid { get; set; }

    public DateTime TransactionDate { get; set; }

    public decimal? TotalAmount { get; set; }

    public string Status { get; set; }

    public virtual ICollection<CarDelivery> CarDeliveries { get; set; } = new List<CarDelivery>();

    public virtual Customer Customer { get; set; }

    public virtual ICollection<CustomerComplaint> CustomerComplaints { get; set; } = new List<CustomerComplaint>();

    public virtual ICollection<CustomerFeedback> CustomerFeedbacks { get; set; } = new List<CustomerFeedback>();

    public virtual Dealer Dealer { get; set; }

    public virtual LetterOfIntent Loi { get; set; }

    public virtual ICollection<PaymentHistory> PaymentHistories { get; set; } = new List<PaymentHistory>();

    public virtual ICollection<SalesAgreementDetail> SalesAgreementDetails { get; set; } = new List<SalesAgreementDetail>();

    public virtual SalesPerson SalesPerson { get; set; }

    // Tambahkan collection untuk CustomerNotification
    public virtual ICollection<CustomerNotification> CustomerNotifications { get; set; } = new List<CustomerNotification>();
}