// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.BO.Models;

public partial class ServiceHistory
{
    public int ServiceId { get; set; }

    public int SalesAgreementDetailId { get; set; }

    public DateTime ServiceDate { get; set; }

    public string ServiceType { get; set; }

    public string Note { get; set; }

    public virtual SalesAgreementDetail SalesAgreementDetail { get; set; }
}