// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.BO.Models;

public partial class VehicleRegistration
{
    public int VehicleRegistrationId { get; set; }

    public int SalesAgreementDetailId { get; set; }

    public string RegistrationNumber { get; set; }

    public string OwnershipBookNumber { get; set; }

    public string TaxStatus { get; set; }

    public string InsuranceStatus { get; set; }

    public virtual SalesAgreementDetail SalesAgreementDetail { get; set; }
}