// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.BO.Models;

public partial class WarrantyClaim
{
    public int WarrantyClaimId { get; set; }

    public int CustomerId { get; set; }

    public int SalesAgreementDetailId { get; set; }

    public DateTime ClaimDate { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual SalesAgreementDetail SalesAgreementDetail { get; set; }
}